### ISSUE TITLE
SelectionPresenter displaying labels

### ISSUE THREAD

**Issue by BogdanNicolau** [Sharlaan/material-ui-superselectfield#1]
When presenting the values, it's usually required to display the labels, instead of the values. Don'thave time for a pull request, but basically (inside SelectField render method):
```
  let presenterValue = []

    const menuItems = children &&
      children.map((child, index) => {
        if (!autocompleteFilter(this.state.searchText, child.props.label)) return
        const isSelected = value.includes(child.props.value)
        if (isSelected) {
          presenterValue.push(child.props.label)
        }
        return (
          <MenuItem
            key={index}
            tabIndex={index}
            value={child.props.value}
            checked={multiple && isSelected}
            leftIcon={(multiple && !isSelected) ? <UnCheckedIcon /> : null}
            primaryText={child}
            disableFocusRipple
          />)
      })
```
Then, SelectionPresenter becomes:

```
<SelectionsPresenter
          disabled={disabled}
          hintText={hintText}
          value={presenterValue.length > 0 ? presenterValue.join(', ') : value}
          displaySelectionsRenderer={displaySelectionsRenderer}
        />
```

**Comment by Sharlaan** [comment]
Usually poeple put "labels" for both innerHTML and value prop.

```
<select>
    <option value="label1">label1</option>
    <option value="label2">label2</option>
    <option value="label3">label3</option>
    <option value="label4">label4</option>
</select>
```

So i implemented the default around the value prop only to make the component as simple to use as possible.
Note: the default autocomplete filter also indexes on the value prop, if no label prop available.

That said, i delegated all responsibility of displaying selected options to the sub-component SelectionsPresenter, which itself rely on the function-prop **"displaySelectionsRenderer"**

I just pushed a new version of CodeExample with a more advance usage of displaySelectionsRenderer

**Comment by BogdanNicolau** [comment]
Not bad, thanks!
