### ISSUE TITLE
Close handler

### ISSUE THREAD

**Issue by deadlyfingers** [Sharlaan/material-ui-superselectfield#10]
Is there merit in adding a close handler for multiple selection cases? In my case I would prefer to wait until multiple selection is done (closed state) then update the results...

**Comment by filipenevola** [comment]
+1

**Comment by Sharlaan** [comment]
Ok from this point of view (one single server request from a close handler, instead of one request per selection) 👍 
This would also solve filipenevola's case :)

Added to my TODO list.

**Comment by barnc** [comment]
+1 for more flexible close handling. I have a multiselect menu that sits above other UI elements, so clicking off it can trigger unwanted user interactions.

I was looking at airbnb filters for examples of multi selections in the wild - they have an 'apply' button below, which would be super useful to have.
 
From my perspective, the ideal solution would be some sort of composable footer which is passed the onclose function.

Great library by the way, works beautifully after having tried a bunch of MUI multi select solutions.

**Comment by Sharlaan** [comment]
Please check v1.5.0 just released, tell me if that works for this usecase.

**Comment by barnc** [comment]
The close functionality is absolutely perfect! Thanks for the rapid response :)

There is possibly an issue with the npm release though - I'm getting a file in the base folder called lib\SuperSelectField.js, rather than it being inside the lib folder. Could be a windows / linux slash issue?

I am also getting issues with custom element height - is that the known issue mentioned in the readme?

**Comment by Sharlaan** [comment]
thanks for the report :)

Regarding custom heights, yes i didnot find a way to autodetect elements heights yet.
So for now, im using a default elementHeight of 36px should be ok for oneliners.
You can specify another value with the prop elemntHeight.
If your items have different heights, you can specify an array of their heights to this prop.

Can you open another issue and tell me more how you install / use superSelectfield to get this slash issue please ?

**Comment by Sharlaan** [comment]
can you retry with v1.5.1 please ?
