### ISSUE TITLE
How do I manually import this project from an outside project with webpack?

### ISSUE THREAD

**Issue by jwmann** [Sharlaan/material-ui-superselectfield#105]
I have an alias in my app that points to this project just outside of it.
This is so I can run this project while I await a PR.

my Webpack config has this
```
  resolve: {
    extensions: ['', '.js', '.jsx', '.json'],
    alias: {
      'material-ui-superselectfield' : __dirname+"/../superselectfield/lib/"
    }
  },
```

and I'm importing like this:
```
import SuperSelectField from 'material-ui-superselectfield';
```

But I get this error when I build my project:
```
ERROR in ../superselectfield/lib/index.js
Module not found: Error: Cannot resolve module 'react-hot' in /Users/jwmann//superselectfield/lib
 @ ../superselectfield/lib/index.js 8:24-53
```

I then add react-hot-loader in the project with `npm i -D react-hot-loader` and now I get this.
```
ERROR in Loader /Users/jwmann//superselectfield/node_modules/react-hot-loader/index.js didn't return a function
 @ ../superselectfield/lib/index.js 8:24-53
```

Keep in mind I have already run `npm i && npm run build` at this point and the app works perfectly fine in its local demo that I access using `npm start`

Is there something I'm missing here? A different build script or something?

Please let me know, thanks.

**Comment by Sharlaan** [comment]
Hi @jwmann 

Have you tried with `npm link` ?

**Comment by jwmann** [comment]
Hi @Sharlaan 

I get the exact same problem.

I also don't think `npm link` will be a viable option for me.

I need to commit this to the repo and have it work in multiple environments.
`npm link` uses symbolic links which don't go into git

Is there some some kind of build script you are using to publish this to `npm`?

**Comment by Sharlaan** [comment]
> Is there some some kind of build script you are using to publish this to npm?

Yes, we use `travis.yml` to setup deployments to gh-pages and npmjs.org. The latter is triggered with a simple increment in package.json version.
