### ISSUE TITLE
Error on clearTextField with keepSearchOnSelect property

### ISSUE THREAD

**Issue by OmanFerrer** [Sharlaan/material-ui-superselectfield#106]
Hi, 
When Escape button is pressed, don't send callback parameter to clearTextField function, then if property 'keepSearchOnSelect' is true, callback is undefined and throw an exception.

Could you see this please?

Thank you!

**Comment by Sharlaan** [comment]
Thanks for your report.
Fix is coming with v1.8.4, but please be patient: Travis publishing is experienceing build problems at the moment.
