### ISSUE TITLE
The pre selected values show up in the Text Field but are not selected when the dropdown menu opens up.

### ISSUE THREAD

**Issue by abhisheknalin** [Sharlaan/material-ui-superselectfield#11]
Hi Sharlaan, 
Great work.
I have been using it for last 1 month and wotks great. Now I have a requirement where I need to show a list of pre-seleced elements. The user can select more or deselect any of the select ones.

The pre selected values do show up in the Text Field but are not selected when the dropdown menu opens up.
Is this a bug?

Regards
Abhishek

**Comment by Sharlaan** [comment]
Yes definitely a bug.

Now have to find out the cause: can you show more code on how you implemented it please ? So i can reproduce before trying to pinpoint the cause, thanks.

**Comment by abhisheknalin** [comment]
`import SelectField from '../../components/SelectField'
` 
```
  handleSelection = (values, name) => {
      this.state.workfile.staffs = values
      this.forceUpdate()
    }
```

  ```
<SelectField 
   name='value2' multiple 
   hintText='Staff Access' 
   onChange={this.handleSelection} 
   value={this.state.workfile.staffs}
   menuStyle={{height:'350px', maxHeight: '230px',overflowY:'auto'}}
   innerDivStyle={{fontSize:'14px', height:'15px'}}
   style={{ color:Colors.grey800, height:'60px', fontSize:'17px'}}>
   {itemStaff}
 </SelectField>
```

Please let me know if you need anything else

**Comment by Sharlaan** [comment]
1. Never ever use forceUpdate(), means almost always an architecture problem
2. never mutate state directly
```js
this.state.workfile.staffs = values
```
should be :
```js
let workfile = { ...this.state.workfile } // neutral copy
workfile.staffs = values
this.setState({ workfile })
```

tell me if it works better ?

**Comment by abhisheknalin** [comment]
Thanks for the advice. I did some reseacrh on this and now understand the importance of it. Wont mutate state directlty again. Thanks.
