### ISSUE TITLE
Select optgroup to select all children

### ISSUE THREAD

**Issue by koltclassic** [Sharlaan/material-ui-superselectfield#111]
It would be nice to have a property on the optgroup list item to allow it to be "selectable". On selection, all of the children of the optgroup would be selected. For example, in CodeExample4 if you were to select the continent "North America", this would select all countries in North America (United States, Canada, etc.). I've attempted to implement this, but it has proven difficult as optgroup menuItems and nested div menuItems look to all be output as a single array. If anybody has an example of this implementation I'd love to see it.

**Comment by davorobadic** [comment]
@koltclassic  Did you find a solution? I am facing the same problem.

**Comment by koltclassic** [comment]
@the-stranger I have not found a solution to this, yet.

**Comment by Sharlaan** [comment]
Please check release 1.9.0
