### ISSUE TITLE
font size on hintTextAutocomplete

### ISSUE THREAD

**Issue by hurano** [Sharlaan/material-ui-superselectfield#116]
Is there any way to change font size on hintTextAutocomplete?

**Comment by Sharlaan** [comment]
check out v1.8.3
Enjoy ! :D

**Comment by hurano** [comment]
which styling properties name can I use for this?

**Comment by hurano** [comment]
@Sharlaan

**Comment by Sharlaan** [comment]
autocompleteStyle

You can check codeExample3.js and in demo action "Autocomplete"

**Comment by hurano** [comment]
I think that is not for hintTextAutocomplete.
I mean placeholder font size before users type.

**Comment by hurano** [comment]
@Sharlaan
