### ISSUE TITLE
Why is there a margin-top on for underline div?

### ISSUE THREAD

**Issue by jwmann** [Sharlaan/material-ui-superselectfield#117]
This margin top of 4px is adding unneeded spacing to my input. 
Removing it makes it looks much better. Is there any particular reason why it's there?

**Comment by Sharlaan** [comment]
I tried to stay inline with Material Guildelines, but they use 8px which i felt quite a lot, so i used twice less.
i won't go to 0.

Source: https://material.io/guidelines/components/text-fields.html#text-fields-layout
