### ISSUE TITLE
Webpack CaseSensitivePathsPlugin throws error

### ISSUE THREAD

**Issue by patoncrispy** [Sharlaan/material-ui-superselectfield#12]
I'm using [create-react-app](https://github.com/facebookincubator/create-react-app), which in turn is using the Webpack [CaseSensitivePathsPlugin](https://github.com/Urthen/case-sensitive-paths-webpack-plugin), which gets upset if (as it sounds) the path required does not match the path on disk in a case-sensitive manner.

I'm getting the following error:

```
'MY_PATH/node_modules/material-ui-superselectfield/lib/superSelectField.js` does not match the corresponding path on disk `SuperSelectField.js`.
```

Manually changing `main` in `package.json` to `lib/SuperSelectField.js` fixes the problem. However, every time I run an NPM command the change is reverted and the problem comes back.

Probably related to issue https://github.com/Sharlaan/material-ui-superselectfield/issues/4!

**Comment by Sharlaan** [comment]
try importing like this:

`import SuperSelectField from 'material-ui-superselectfield/lib/SuperSelectField'`

**Comment by patoncrispy** [comment]
That workaround works, thanks!
