### ISSUE TITLE
bumping node engine version is major update/breaking change

### ISSUE THREAD

**Issue by tomasztunik** [Sharlaan/material-ui-superselectfield#126]
Our CI just complained after superselectfield package upgrade - we've noticed that required engine version jumped from >= 6 to 7 (and looking at blame to 8.9 in the meantime) and as a breaking change it should require major version bump to avoid people having issues where on prod/staging/test env they might still have Node 6 running (still in active LTS state).

Is there a reason for engine update (especially to non stable version?) or just future proofing?

**Comment by Sharlaan** [comment]
is this issue still valid as of today ?
[current active LTS version is 8](https://nodejs.org/en/)

**Comment by tomasztunik** [comment]
https://github.com/nodejs/Release#release-schedule node 6 will be in active maintenance until April 2019 so there will be a lot of projects still running it. 

But the issue here is not upgrading this requirement - this is perfectly fine. It's doing that using patch version bump where it can block continuous integration after a fresh install of dependencies on the test env if you did not have your dependencies locked to particular version but allowed patch updates according to SEMVER  - like in our case happened. Gladly for us, it did not happen in a critical moment but if it was during some kind of major push it could easily cost us extra 30-40 minutes to solve this.

So my only request is that to keep all these poor CIs in mind next time when bumping package dependencies :)

**Comment by Sharlaan** [comment]
Ok thanks for the explanation and the link, this makes the topic clearer :)

Ok so i'll just close this and keep it as a reference until April 2019 ^^
