### ISSUE TITLE
"No match found" placeholder is hidden

### ISSUE THREAD

**Issue by OmanFerrer** [Sharlaan/material-ui-superselectfield#128]
Hi, 
"No match found" placeholder is hidden. See below: 
![select1](https://user-images.githubusercontent.com/7102601/34787763-2d6c2c16-f617-11e7-8059-2d2b09f91060.png)

Then placeholder appear when I scroll into the popover:
![select2](https://user-images.githubusercontent.com/7102601/34787836-74692196-f617-11e7-86b1-38177b259153.png)

That's because ```popoverHeight``` it's calculating incorrectly:
```
const containerHeight =
      (Array.isArray(elementHeight)
        ? elementHeight.reduce((totalHeight, height) => totalHeight + height, 6)
        : elementHeight * (nb2show < menuItems.length ? nb2show : menuItems.length) + 6) || 0;

var popoverHeight = autoCompleteHeight + (containerHeight || noMatchFoundHeight) + footerHeight;
```

When no results is found, ```containerHeight``` has value 6 and ```noMatchFoundHeight``` is never setting. 
I think if you are adding the value 6 on each case (when ```elementHeight``` is an array or not), it could be added in ```popoverHeight```'s calculation. Then the code would look like this and the problem would be solved:

```
const containerHeight =
      (Array.isArray(elementHeight)
        ? elementHeight.reduce((totalHeight, height) => totalHeight + height, 0)
        : elementHeight * (nb2show < menuItems.length ? nb2show : menuItems.length)) || 0;

var popoverHeight = autoCompleteHeight + (containerHeight || noMatchFoundHeight) + footerHeight + 6;
```

Could you consider this solution please?
Thank you!!

**Comment by ghost** [comment]
Any news about this @Sharlaan ?

**Comment by Sharlaan** [comment]
Fixed with v1.8.10

Enjoy :p

**Comment by ghost** [comment]
You're a f... genius!! Thx :smile:

**Comment by Sharlaan** [comment]
Correction: @OmanFerrer is the genius :)
