### ISSUE TITLE
Should not increase popover height for menuCloseButton if multiple if false.

### ISSUE THREAD

**Issue by mitchvoll** [Sharlaan/material-ui-superselectfield#129]
If a prop for menuCloseButton is passed then the footer height is set to 36 regardless of whether the menuCloseButton is rendered (for multiple mode). I think there should be a check for `multiple && menuCloseButton`

**Comment by Sharlaan** [comment]
Just to be sure, are you suggesting that in single mode (multiple = false), SSF should ignore anything passed to the `menuCloseButton` prop ?

**Comment by mitchvoll** [comment]
That's the current logic right? If in multiple mode then the `menuCloseButton` is not displayed however the footer height is calculated just on if `menuCloseButton` prop is passed.
``` javascript
    const footerHeight = menuCloseButton ? 36 : 0
```
But the `menuCloseButton` isn't even rendered if the component is not in multiple mode so you just end up with a bunch of padding at the bottom

**Comment by Sharlaan** [comment]
ok thanks.

commit pushed, it will be in for next release.
