### ISSUE TITLE
Doesn't work when count of children less than 2

### ISSUE THREAD

**Issue by krolser** [Sharlaan/material-ui-superselectfield#13]
Sometimes needs to add only one or zero items to the children (one or zero items to the optgroup). Your code fails on this situation.

Problems on lines
https://github.com/Sharlaan/material-ui-superselectfield/blob/master/lib/SuperSelectField.js#L452
https://github.com/Sharlaan/material-ui-superselectfield/blob/master/lib/SuperSelectField.js#L558
etc.

Example code

```js
import React from 'react';
import ReactDOM from 'react-dom';
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
import SuperSelectField from 'material-ui-superselectfield/lib/SuperSelectField'

ReactDOM.render(
  <MuiThemeProvider>
    <div>
      <SuperSelectField>
        <span value={'A'} >A</span>
      </SuperSelectField>
    </div>
  </MuiThemeProvider>,
  document.getElementById('root')
);
```

or example with one optgroup

```js 
import React from 'react';
import ReactDOM from 'react-dom';
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
import SuperSelectField from 'material-ui-superselectfield/lib/SuperSelectField'

ReactDOM.render(
  <MuiThemeProvider>
    <div>
      <SuperSelectField multiple>
        <optgroup label="A">
          <span value={'A1'} >A1</span>
          <span value={'A2'} >A2</span>
        </optgroup>
      </SuperSelectField>
    </div>
  </MuiThemeProvider>,
  document.getElementById('root')
);
```

This happens because children in this case is a single object but not an array how you expect.

**Comment by Sharlaan** [comment]
Thanks for your report, i just pushed a fix.

Can you retry with v1.5.1, please ?

**Comment by krolser** [comment]
I used lates version from github.

First case: everything is ok
Second: 
```
Uncaught TypeError: fixedChildren.reduce is not a function
    at SelectField.render (SuperSelectField.js:507)
```

**Comment by Sharlaan** [comment]
Damn it! ok i'll re-test again :p

The problem with this mess is that React doesnot return, in the case of one single child, an array with one item, but the item as an object... hence all the `not a function` errors about array methods applied to an object.

**Comment by Sharlaan** [comment]
Ok i just pushed a version that should fix both issues, please confirm.

**Comment by krolser** [comment]
Previous cases works great. But I found another

Case 3:

```
      <SuperSelectField multiple value={[]}>
        <optgroup label="A">
          <span value={'A1'} >A1</span>
          <span value={'A2'} >A2</span>
        </optgroup>
        <optgroup label="B">
          <span value={'B1'} >B1</span>
        </optgroup>
      </SuperSelectField>
```
```
SuperSelectField.js:324 Uncaught TypeError: child.props.children[Symbol.iterator] is not a function
```

Case 4:
Also I found intresting behaviour. Code:
```
      <SuperSelectField multiple value={[]}>
        <optgroup label="A">
          <span value={'A1'} >A1</span>
        </optgroup>
      </SuperSelectField>
```
When I click to the menuitem many times I see `A, A, A, A, A, A, A, A`

**Comment by Sharlaan** [comment]
Added your edge cases and others into CodeExample1.js

Can you tell me if those work for you ?

**Comment by krolser** [comment]
I checked it.
Everything is fine.
Thanks.
