### ISSUE TITLE
font size on hintTextAutocomplete (placeholder font size)

### ISSUE THREAD

**Issue by hurano** [Sharlaan/material-ui-superselectfield#130]
Is there any way to change font size on hintTextAutocomplete (placeholder font size before users type)

Thank you,
Hiromi

**Comment by Sharlaan** [comment]
Please check styling documentation for the prop `autocompleteStyle`
also CodeExample3.js provides an example with the `state32` selectfield.

**Comment by Sharlaan** [comment]
Ok next version should not raise any error when passing a node in the prop `hintTextAutocomplete`

Please check CodeExample3 after release 1.8.11
