### ISSUE TITLE
Error "Cannot read property 'some' of null" in multiple mode

### ISSUE THREAD

**Issue by TarikHuber** [Sharlaan/material-ui-superselectfield#135]
Hi @Sharlaan ,

Just to forward a issue I got over [React Most Wanted](https://github.com/TarikHuber/react-most-wanted).

First I was thinking that the issue was in our implementation of SuperSelectField to ReduxForm but it seems that it is a SuperSelectField issue. When using the multiple mode we get the error message:
"Cannot read property 'some' of null" in this part of the code

```json
    _this.handleMenuSelection = function (selectedItem) {
      return function (event) {
        event.preventDefault();
        var selectedItems = _this.state.selectedItems;

        if (_this.props.multiple) {
          var selectedItemExists = selectedItems.some(function (obj) {
            return areEqual(obj.value, selectedItem.value);
          });
```

It seems that selectedItems are null. 

To be sure that the error is not form our implementation to ReduxForm I copied the example from "example2" into our code and the same error appears. 

If I find time I will take a look on it myself but if you have it would be great to fix thiss issue. It seems like a issue that could affect everyone who is using the multiple mode.

**Comment by Sharlaan** [comment]
I think the error might come from :
```js
componentWillReceiveProps (nextProps) {
    if (!areEqual(nextProps.value, this.state.selectedItems)) {
      this.setState({ selectedItems: nextProps.value })
    }
```
... and here the proptype definition for value:  
`const checkFormat = (value) => value.findIndex((v) => typeof v !== 'object' || !('value' in v))`  
```js
value: (props, propName, componentName, location, propFullName) => {
    const { multiple, value } = props
    if (multiple) {
      const index = checkFormat(value)
      if (!Array.isArray(value)) {
        return new Error(`
          When using 'multiple' mode, 'value' of '${componentName} ${props.name}' must be an array.
          Validation failed.`)
      } else if (index !== -1) {
        return new Error(`
          'value[${index}]' of '${componentName} ${props.name}' must be an object including a 'value' property.
          Validation failed.`)
      }
```

so if value is set to wrong type (Array when multiple, primitive if not multiple), the above proptype snippet should throw an explicit error if value is set to null/undefined for any reason.

Can you give an example to repoduce this issue please, as my examples don't throw ?

**Comment by TarikHuber** [comment]
Hi,

Just change the SSF in [this file](https://github.com/TarikHuber/react-most-wanted/blob/master/src/components/Forms/TaskForm.js) to multiple.

Even if you don't use the ReduxForm wrapper it happens.

**Comment by Sharlaan** [comment]
Ok i reproduced the issue and found out that my initial guess were correct:
- the proptype check for value is broken somehow, it should have yelled at me when i put multiple prop in CodeExample1 where only single values are set.  
- you did not set `value` type properly depending on multiple mode. More specifically `Field` seems to be uncontrolled, while SSF is a controlled-only component. This means it requires value and onChange handler. I did not find these props in RMW `Task.js`

**Comment by Sharlaan** [comment]
Hi,
Can you try with v1.8.9 : it should spit an error about invalid value prop ?

**Comment by Sharlaan** [comment]
closing since no report
