### ISSUE TITLE
FloatingLabel problem

### ISSUE THREAD

**Issue by ghost** [Sharlaan/material-ui-superselectfield#137]
Hi.
When I add the floatingLabel option, this label block the normal behavior of the component. I need to do two clicks to show the options when there aren't options selected.

I checked the same behavior in the live demo.

Why this happen? Any fast solution?

**Comment by Sharlaan** [comment]
Hi, nice catch there !

It actually work properly if you do NOT click on the floating label text, click :
- in the free space between the label and the arrow
- on the arrow

But indeed clicking on the label triggers only the shrinking of the label, but does not trigger the opening of the options menu...

I'll try to push a fix for tomorrow.

Thanks for your report

**Comment by ghost** [comment]
Thank you for the quick answering.

I'll waiting the fix :)

Regards

**Comment by Sharlaan** [comment]
Check for the newly released v1.8.6, enjoy ^^

**Comment by ghost** [comment]
@Sharlaan you are a genius! Thx you so much! :)
