### ISSUE TITLE
How to style the popover element?

### ISSUE THREAD

**Issue by barrymichaeldoyle** [Sharlaan/material-ui-superselectfield#139]
I'm working on a project where the application's base styles have a transition effect which is interfering with the superselectfield popover (I'm using a group select).

We're using styled components, it is possible to add a class to the root div of the popover?

Not sure how I can disable transitions across the entire element otherwise.

**Comment by Sharlaan** [comment]
Hello,

Indeed, you pointed me at [this line](https://github.com/Sharlaan/material-ui-superselectfield/blob/master/src/SuperSelectField.js#L376) showing the Popover's styles are not exposed, hence not customisable ...
I can expose the Popover's className prop, but can you show a sample code showing how yours transitions are applied to SuperSelectField ? Maybe i can find a better suited solution ?

**Comment by barrymichaeldoyle** [comment]
I wrote that as work and now I'm home so I can't really show the code. But my solution to similar problems was to use a className. So if you could expose the Popover's className prop that would be life saving! :)

**Comment by Sharlaan** [comment]
Can you try with v1.8.7 ?

**Comment by barrymichaeldoyle** [comment]
Yeah it's good, thanks man :)

**Comment by Sharlaan** [comment]
I'm actually not sure it is working:
for example i created a class `popover { border: 1px solid red }`
and imported it into the component using SSF => the class didnot applied even though i retrieved it in Elements panels in DevTools...

**Comment by barrymichaeldoyle** [comment]
You're missing the `.` it should be `.popover { border: 1px solid red; }`

**Comment by Sharlaan** [comment]
rofl i feel noob !
thanks Barry it works ^^
Enjoy

**Comment by barrymichaeldoyle** [comment]
Happens to the best of us ;) Thanks for everything man :) Appreciate your hard work on this repo :D

**Comment by barrymichaeldoyle** [comment]
Could you add me as a collaborator on npmjs? My username is `barrymichaeldoyle`
