### ISSUE TITLE
Port to material Next branch

### ISSUE THREAD

**Issue by stunaz** [Sharlaan/material-ui-superselectfield#14]

**Comment by kjg531** [comment]
It would be nice if we could get this closer visually to 0.17+?

**Comment by Sharlaan** [comment]
visually ? what do you mean ?

SuperSelectField is composed with components from MaterialUI 0.17

On this topic i'll refactor SuperSelectField when M-UI will hit 1.0 release.

**Comment by kjg531** [comment]
Yes, visually. It would be nice if the visuals of this were closer to MUI's Select. I'm on the road at the moment but let me know if you would like a more detailed NIT.

P.S.  @Sharlaan thank you so much for your contribution, this is awesome!

**Comment by Sharlaan** [comment]
Yes, please more details.

**Comment by frankbolviken** [comment]
I would actually argue that because of the rapid development in the react world + hype of material-ui, that this should be prioritised. Most people who go into the material-ui framework these days jumps on the Next branch.. It's beta16 now.

**Comment by TarikHuber** [comment]
Yes but with missing components! It would be good to have a seperated branch in preparation for v16 but it makes no sense to sync them both until material-ui v1 is released

**Comment by frankbolviken** [comment]
What are the components that you are missing?

**Comment by Sharlaan** [comment]
for one: Popover

but more importantly, all material-ui components have changed their implementations/properties
i think we'll have to rewrite superSelectField from scratch, anyways

**Comment by TarikHuber** [comment]
@Sharlaan we could also try to use this project https://github.com/paypal/downshift as base. It comes from PayPal and they should know what they are doing ;)

**Comment by stunaz** [comment]
`Popover` is there https://material-ui-next.com/demos/popovers/

**Comment by Leenzur** [comment]
+1
