### ISSUE TITLE
BREAKING ISSUE: Miss Spelling

### ISSUE THREAD

**Issue by patrickml** [Sharlaan/material-ui-superselectfield#15]
There is a miss-spelling in the package.json `lib/super*` vs `lib/Super*`; this is breaking eslint and making some application unable to deploy that have strict checks.

Reference:
https://github.com/benmosher/eslint-plugin-import/issues/761#issuecomment-284781536

Line to Fix: 
https://github.com/Sharlaan/material-ui-superselectfield/blob/master/package.json#L16

**Comment by Sharlaan** [comment]
already fixed it internally, for next update.

check [issue #12](https://github.com/Sharlaan/material-ui-superselectfield/issues/12)

**Comment by patrickml** [comment]
Anyway to push early release?

**Comment by Sharlaan** [comment]
~~maybe if you make a PR ill merge it.~~

release 1.5 includes this path fix.
Tell me if that works.

**Comment by Sharlaan** [comment]
Closing, assuming it's fixed.
