### ISSUE TITLE
Feature Request: Modify 'select all' button to select returned values from search query

### ISSUE THREAD

**Issue by koltclassic** [Sharlaan/material-ui-superselectfield#158]
## Expected Behavior
It would be useful to have the "select all" button select only the results of a search query when a search query is entered. 

## Current Behavior
Currently the "select all" button selects all of the select field's children regardless of the search query that is entered.

![superselectfield_select_all_search](https://user-images.githubusercontent.com/6091219/38092810-48adb708-3337-11e8-9c6a-10f329b5d2dc.gif)

## Possible Solution
I would think that the `selectAll()` method of `SuperSelectField.js` would need to be modified to target the result of the query rather than the initial dropdown options, possibly something like a `currentChildren` value initally being equal to `children`, but updating inside of `handleTextFieldAutocompletionFiltering`

**Comment by Sharlaan** [comment]
good point 👍 

i'll work on it soon.

**Comment by Sharlaan** [comment]
1.9.1 released, enjoy
