### ISSUE TITLE
[QUESTION] floatingLabelFixed prop (or style) available?

### ISSUE THREAD

**Issue by m-o-leary** [Sharlaan/material-ui-superselectfield#167]
Hi,

I like this component and am trying to use it in my application instead of a normal select. The reason is the amount of entries is > 500 so I like your autocomplete functionality with the search.

However one thing I am concerned about is the styling of this component. 
If I am to use this, the look must not differ from normal material-ui select.
The `floatingLabelFixed` prop is used on all my fields (text and select) currently and I need to have it on this also.

I've checked the readme but don't see a prop for this there, am I missing something?

If you could add this I would be very grateful! 

Thanks,
M

**Comment by Sharlaan** [comment]
Hello,

Thanks for your interest in my component.

I'm slightly confused in what you want exactly :
- `floatingLabelFixed` just prevents the label shrinking animation depending if value is null or not. It has nothing to do with label styling.
- you wrote being concerned with styling, look being different from official M-UI v0.x version

Can you be more explicit please ?

PS: there is a `floatingLabelStyle` prop in readme

**Comment by m-o-leary** [comment]
Hi, 

Thanks for responding. 

So with current select field I have the prop `floatingLabelFixed={true}` which, as you know, keeps the floating label positioned above the input regardless of whether or not value is null.

With this prop set I then have hint text in the component which is how all my selects and text fields are setup.

I just want to replicate this with your component.
In the example picture, the top one is a normal select, bottom is your component:
![image](https://user-images.githubusercontent.com/24975408/42124899-a9c3eb32-7c63-11e8-952b-efe6354c7136.png)


So is it possible to have "Work Item Tool" always positioning like the following?
![image](https://user-images.githubusercontent.com/24975408/42124907-d71d7670-7c63-11e8-8593-ad2304150e20.png)

On the styling; I have to manually add a margin of 20px to the top of the element to have a similar height to normal M-UI v0.x select - the M-UI v0.x select has same height regardless of floating label present or not. I am assuming when I have a fixed floating label it will all look OK though.

**Comment by Sharlaan** [comment]
Ok just made a release which should be available in next 30mins.

If you specify BOTH `floatingLabel` and `hintText`, then the floatingLabel will remain fixed no matter what.

**Comment by m-o-leary** [comment]
Hi,

Appreciate the fast turnaround.

Stupid question - how do I get this latest change? When I `npm i material-ui-superselectfield` I get the latest released version `material-ui-superselectfield@1.9.4`  but when I use it as follows:

```
      import SuperSelectField from 'material-ui-superselectfield';
      ...
      renderSelect = list => {
        return _.map(list, (tool,i) => {
          return <div key={i} value={tool[globals._FIELD]}>{tool['human']}</div>
        })
      }
      ...
        <SuperSelectField
            name='tool'
            floatingLabel='Work Item Tool(s)'
            hintText='Select a tool'
            value={tool}
            onChange={handleChange}
            style={{width: 256, marginTop: 20}}
          >
          {
              :: this.renderSelect(newDataSource)
          }
          </SuperSelectField>
```

resulting in the following:

![image](https://user-images.githubusercontent.com/24975408/42167063-c2fcfcd6-7e04-11e8-84a3-3b2479068a27.png)

so I'm not seeing the change that you implemented I think...
sorry!

**Comment by Sharlaan** [comment]
Indeed i found out Travis failed to build ...

so the v1.9.4 has the updated src, but the old built lib .... *sigh*

**Comment by Sharlaan** [comment]
ok, try v1.9.5

**Comment by m-o-leary** [comment]
Thanks!
