### ISSUE TITLE
Upgrade to 1.5.0 results in module not found error

### ISSUE THREAD

**Issue by marcacyr** [Sharlaan/material-ui-superselectfield#17]
Something with the build for 1.5.0 has broken the ability for the package to be found inside of node_modules.

Prior to 1.5.0 (working on something with it yesterday actually, on 1.1.0):
`import SuperSelectField from 'material-ui-superselectfield';` -- this was working just fine.

Now, after updating to 1.5.0, it cannot find the file. I looked into node_modules and I think I see the issue.

In 1.1.0, the file structure for the built version was: `material-ui-superselectfield > lib > SuperSelectField.js`

Now, in 1.5.0, the file structure for the built version is: `material-ui-superselectfield > lib > {empty directory}`, but the root directory has a file called `lib\SuperSelectField.js`

So, node/npm have no idea how to resolve this path. The paths expected are `root > lib > file`, so if the file is not there, things blow up.

I have not poked around enough yet to know what was changed that caused this.

**Comment by marcacyr** [comment]
Wait, I think I have found the issue. In your scripts you have `"prepublish": "babel src/SuperSelectField.js -o lib/SuperSelectField.js",`

I think it is just an unintentional typo (if I had to guess) -- you or whoever wrote the code probably intended the `out (-o)` to be `lib/SuperSelectField.js`

edit -- I looked too fast and thought `/` was `\`, but now see it's not wrong... looking to see what else it could be.

**Comment by Sharlaan** [comment]
I'm only maintainer of this project :)

thanks for the report, you are second one reporting this issue but i also think it may be provoked from this line, but i don't understand why yet...

I wrote this prepublish script to babelify the SuperSelectField.js written in ES7, into a ES5 compatible version in the folder /lib
... then publish only this last file.

Usually i publish with `npm publish` but exceptionnally i used `yarn publish`
maybe it failed somehow ?

I'm not even sure my publishing flow is correct ? Ideally i would want to expose in node_modules only the SuperSelectField.js from /lib folder. I'm on Windows.

**Comment by Sharlaan** [comment]
i just made another publish (v1.5.1) using regular `npm publish` this time, please tell me if this fixes the issue.

**Comment by marcacyr** [comment]
Thanks @Sharlaan!! I have run into issues myself in recent months with Yarn - I love it, but it is still new and I'm not surprised there are still hiccups sometimes. Will try it out and report back here!

**Comment by marcacyr** [comment]
@Sharlaan Got things working again - bump to 1.5.1 did it!

There is a slight issue in the package.json, I'll write another issue for it.
