### ISSUE TITLE
Menu is not opened on arrow click

### ISSUE THREAD

**Issue by maalej** [Sharlaan/material-ui-superselectfield#175]
hi,
Thank you very much for this awesome component.
When I click on the arrow, the menu does not open, I have to click twice.
Thanks

**Comment by Sharlaan** [comment]
Good point thanks.

Can you try with release 1.9.8 ?

**Comment by Sharlaan** [comment]
Sorry, i got some issues with npm publish, should be fine now with v1.9.8

**Comment by maalej** [comment]
thank you
