### ISSUE TITLE
Error in safari (and probably other browsers): TypeError: Object.entries is not a function

### ISSUE THREAD

**Issue by darrenhewson** [Sharlaan/material-ui-superselectfield#19]
The error is:
> TypeError: Object.entries is not a function. (In 'Object.entries(t)', 'Object.entries' is undefined)
> SuperSelectField.js:19

You can see it here: [https://sharlaan.github.io/example3](https://sharlaan.github.io/example3)

It only occurs when there are 2  or more instances of SuperSelectField on a page. 

It looks like object.entries has limited browser support, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries#Browser_compatibility 

So there are probably issues in IE and Safari/IE on mobile devices as well.

**Comment by Sharlaan** [comment]
Thanks for your report.
I thought Babel would transpile it, ill i'll try to find a solution....

**Comment by Sharlaan** [comment]
I just pushed another version compiled differently. It is in `/lib` folder.

Can you try it and tell me if this solves the issue ?

**Comment by darrenhewson** [comment]
Hey @Sharlaan, I tested /lib/SuperSelectField.js in a couple of my projects and it seems to have resolved the issue in Safari.

Thanks
