### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by srckot** [Sharlaan/material-ui-superselectfield#191]
Hey there, 
Not quite sure if i'm to dumb to install or to dumb to use it... or if this is some kind of incompatibility...
I'm trying to implement the superselectfield in an existing .NET Core React Project. 
The dependencies were already installed in that project, so i just had to add the SuperSelectField, which i did. 
Now i created a dummy component, just returning a dummy SuperSelectField, but when it renders I'm always getting a blank screen. 

Here's the render section.
`render() {`
`        return (`
`            <SuperSelectField`
`                name='state11'`
`                hintText='Single value'`
`                value=""`
`                style={{ minWidth: 150, margin: 10 }}>`
`                    <div value='A'>Option A</div>`
`                    <div value='B'>Option B</div>`
`                    <div value='C'>Option C</div>`
`            </SuperSelectField>`
`        );`
`    }`

Console is like "SuperSelectField says no"...
Could anyone please help me out right here?

Ps: ES5 / Versions according to package.json:
react 16.5.2
react-dom 16.5.2
material-ui 0.20.2 
material-ui-superselectfield ^1.10.0

Greetings, 
srckot

**Comment by Sharlaan** [comment]
Hello,

This is a usage problem, not an issue (at first glance).
Please use StackOverflow, here is for issues with full and minimal reproducible report.

For instance, your console message is totally meaningless.
Also the value property does not seem connected at all to your context, i suggest you learn how inputs work with React state.
