### ISSUE TITLE
Unable to change data

### ISSUE THREAD

**Issue by eely22** [Sharlaan/material-ui-superselectfield#22]
We are attempting to use two select fields, one to select states and another to select counties. The state select field is pre-populated, that is, it just always has the list of 50 states.

The list of counties is initially blank. Depending on the state the user selects, the list of counties would then get populated only with the counties from the state(s) that are selected.

The issue is, this doesn't work. If we give see a select field a blank list, and then later update it with a list of children, it doesn't update and no options appear in the drop-down. Here is the select field in the render function():
```
<SuperSelectField
    name="Hi"
    hintText="Testing..."
    multiple
    checkPosition='left'
    selectionsRenderer={this.handleCustomDisplaySelections}>

    {this.state.items}

  </SuperSelectField>
```

Initially, this.state.items is set to:
```
        var items = [];
        return items;
```

Then, we change the list after 3 seconds:
```
componentDidMount = () => {
        window.setTimeout(() => {

            var items = [];
            items.push(<div key="Hello" value="Hello">Hello</div>);
            items.push(<div key="Again" value="Again">Again</div>);

            this.setState({
                items: items
            })
            console.log('updated')
        }, 3000);
    };
```

There is no error in the console, but the control will not allow us to select anything. It just doesn't work, the drop-down never opens.

If, instead, I populate the select field initially with some data like this:
```
        var items = [];
        items.push(<div key="Hi" value="Hi">Hi</div>);
        items.push(<div key="World" value="World">World</div>);
        return items;
```

Then it works. So I would see the two options 'Hi' and 'World' in the drop-down, and then after 3 seconds, I see the 'Hello' and 'Again' options. 

So giving the select field a blank list, and then later populating it with data does not work. The expected behavior, of course, is that the drop down gets the new values when they are specified.

**Comment by Sharlaan** [comment]
Ok thanks for the very clear report.

Sound like a typical componentWillReceiveProps problem, i'll investigate ...

**Comment by Sharlaan** [comment]
Ok i found the bug i've just forgot this :
```js
if (!areEqual(nextProps.children, this.props.children)) {
    const itemsLength = this.getChildrenLength(nextProps.children)
    this.setState({
        itemsLength,
        showAutocomplete: itemsLength > this.props.showAutocompleteThreshold
    })
}
```
in `componentWillReceiveProps`

Thanks for th example with US states/counties, i'll make a 5th CodeExample.js for you and others.

**Comment by eely22** [comment]
Thanks, can confirm this works.

**Comment by Sharlaan** [comment]
Thanks for confirmation.

I'll make a release for Monday hopefully

**Comment by TarikHuber** [comment]
I have the same issue. Using react-redux on version 1.5.2.

The whole code:
```js

import React, { Component, PropTypes } from 'react';
import FlatButton from 'material-ui/FlatButton/FlatButton';
import SuperSelectField from 'material-ui-superselectfield'

class AutoCompleteList extends Component {

  componentWillMount() {
    const { entityName, fetchNextPage } = this.props;

    fetchNextPage(entityName);
  }


  render() {
    const {
      messages,
      entities,
      fetchNextPage,
      name,
      value,
      onChange,
      hintText,
      entityName
    } = this.props;

    const dataSourceNodes = entities[entityName].list.map((item, index) => (
      <div key={index} value={item.id} label={item.name}>{item.name}</div>
    ))

    console.log(dataSourceNodes);

    return (
      <SuperSelectField
        name={name}
        showAutocompleteThreshold={2}
        hintText={hintText}
        onChange={onChange}
        value={value}
        hoverColor='rgba(3, 169, 244, 0.15)'
        anchorOrigin={{ vertical: 'bottom', horizontal: 'left' }}
        style={{ width: 200, marginTop: 20 }}
        menuCloseButton={<FlatButton label='close' hoverColor={'lightSalmon'} />}>
        {dataSourceNodes}
      </SuperSelectField>
  );
}
}

AutoCompleteList.propTypes = {
  messages: PropTypes.object.isRequired,
  entities: PropTypes.object.isRequired,
  fetchNextPage: PropTypes.func.isRequired,
  entityName: PropTypes.string.isRequired,
  name: PropTypes.string.isRequired,
  hintText: PropTypes.string,
  value: PropTypes.any,
  onChange: PropTypes.func,
};

export default (AutoCompleteList);


```

**Comment by Sharlaan** [comment]
Is dataSourceNodes updating properly after `fetchNextPage(entityName)` received its response from server ?

Note about "Using react-redux on version 1.5.2." : shouldnot it be v5+ ?

**Comment by TarikHuber** [comment]
Yes, dataSourceNodes is updating properly.
Version of SuperSelectField: 1.5.2
Sorry the connection to the store I save into a seperate file:

```js

import { connect } from 'react-redux';
import {openDialog, closeDialog} from '../../actions/dialogs';
import {	fetchNextPage} from '../../actions/lists';
import AutoCompleteList from '../../components/Lists/AutoCompleteList';

function mapStateToProps(state) {
	const { intl, auth, entities} = state;

	return {
		messages: intl.messages,
		auth,
		entities
	};
}

const mapDispatchToProps = (dispatch) => {

	return {
		openDialog: (dialogID)=>{
			dispatch(openDialog(dialogID));
		},
		closeDialog: (dialogID) => {
			dispatch(closeDialog(dialogID));
		},
    fetchNextPage: (listName) => {
      dispatch(fetchNextPage(listName));
    },

	}
}

export default connect(mapStateToProps, mapDispatchToProps)(AutoCompleteList);

```

The fetchNextPage action is ending in a reducer and this changes the state adding to the entities[entityName].list the array result from an API call. So moving the entities[entityName].list into the parent component would have the same result. The `console log` is changing as it should from [] to an array with some objects in it. 

I also tryed to leave the component in the appliaction and return to it. In that case the SuperSelctField renders correctly. 

Thank you for the fast response :)

**Comment by Sharlaan** [comment]
"I also tryed to leave the component in the application and return to it. In that case the SuperSelctField renders correctly."
er... are you saying the superSelectField isnot working when modularized out of the parent component ?

**Comment by TarikHuber** [comment]
I mean that it renders correctly only when the state is changed before the initial rendering of the SuperSelectField.

When I open the form where I use the SuperSelectField it doesn't render how it shuld but the state changes how it should. Going away from that form to something else in the application and then going back (the state stays the same) to the form where I use SuperSelectField it renders correctly.

**Comment by TarikHuber** [comment]
I have tried the solution from the begining of the issue and it helped. Adding a non empty array with more than one item helps. There must be more then one item!

Full example:

```js

import React, { Component, PropTypes } from 'react';
import FlatButton from 'material-ui/FlatButton/FlatButton';
import SuperSelectField from 'material-ui-superselectfield'

class AutoCompleteList extends Component {

  componentWillMount() {
    const { entityName, fetchNextPage } = this.props;

    fetchNextPage(entityName);
  }


  render() {
    const {
      entities,
      name,
      value,
      onChange,
      hintText,
      entityName
    } = this.props;

    let list=entities[entityName].list;

    if(Array.isArray(list) && list.length===0){
      list=[
        {id:0, name: 'Empty'},
        {id:1, name: 'Empty'},
      ]
    }

    let dataSourceNodes = list.map((item, index) => (
      <div key={index} value={item.id} label={item.name}>{item.name}</div>
    ))

    console.log(dataSourceNodes);

    return (
      <SuperSelectField
        name={name}
        showAutocompleteThreshold={2}
        hintText={hintText}
        onChange={onChange}
        value={value}
        hoverColor='rgba(3, 169, 244, 0.15)'
        anchorOrigin={{ vertical: 'bottom', horizontal: 'left' }}
        style={{ width: 200, marginTop: 20 }}
        menuCloseButton={<FlatButton label='close' hoverColor={'lightSalmon'} />}>
        {dataSourceNodes}
      </SuperSelectField>
  );
}
}

AutoCompleteList.propTypes = {
  messages: PropTypes.object.isRequired,
  entities: PropTypes.object.isRequired,
  fetchNextPage: PropTypes.func.isRequired,
  entityName: PropTypes.string.isRequired,
  name: PropTypes.string.isRequired,
  hintText: PropTypes.string,
  value: PropTypes.any,
  onChange: PropTypes.func,
};

export default (AutoCompleteList);

```

Connection to the store is in a seperate file.

Could it be that I have a older version or that the current version doesn't have the fix from abowe?
From the `package.json` it is 1.5.2.

**Comment by Sharlaan** [comment]
check CodeExample5 where DataSource changes from [] to filled Array.

I think you need componentDidMount.

**Comment by TarikHuber** [comment]
Same with componentDidMount :(

Do you mean [this ](https://github.com/Sharlaan/material-ui-superselectfield/blob/master/src/CodeExample5.js) example.

**Comment by Sharlaan** [comment]
yes this one, but i realized something else: i forgot to release the fix of this issue ...

i apologize i'll try to release v1.5.3 this week.

**Comment by TarikHuber** [comment]
Sorry but the [example](https://github.com/Sharlaan/material-ui-superselectfield/blob/master/src/CodeExample5.js) has a static and full source all the time.

That's what I was thinking of all the time ;) I couldn't find your fix in the repo and also not in my localy installed node_module code. 

I'm glad we found the problem :) Thank you very very mutch! You have a beer from me when you come to germany.

**Comment by Sharlaan** [comment]
lol yep a full pack !

**Comment by Sharlaan** [comment]
1.5.3 released ! tell me if it solves your issue please.

**Comment by TarikHuber** [comment]
Yes. Greate work :)
