### ISSUE TITLE
How can SuperSelectField be used with redux-form?

### ISSUE THREAD

**Issue by pfortes** [Sharlaan/material-ui-superselectfield#24]
Does anyone know how is it posible to use Super Select Field with redux-form?

I have tried adapting a wrapper using the code redux-form-material-ui uses to create components but i have not managed to make it work.

What i have tried so far is rendering a redux-form field:

` <Field
                  name='Accesosrios__c'
                  component={SuperSelectFieldWrapper}
                  multiple
                  hintText='Accesorios'>
                    {this.props.accesorios.map((val, i) => {
                      console.log('en map ', val)
                      return (
                        <div key={'acc_'+i} value={val}>{val}</div>
                      )
                    })}
                  </Field>`

Using the next component Wrapper:

`
        import SuperSelectField from 'material-ui-superselectfield'
    import { Component, createElement } from 'react'

    /**
     * Creates a component class that renders the given Material UI component
     *
     * @param MaterialUIComponent The material ui component to render
     * @param mapProps A mapping of props provided by redux-form to the props the Material UI
     * component needs
     */
    function createComponent(MaterialUIComponent, mapProps) {
      class InputComponent extends Component {
        getRenderedComponent() {
          return this.refs.component
        }

        render() {
          return createElement(MaterialUIComponent, {
            ...mapProps(this.props),
            ref: 'component'
          })
        }
      }
      InputComponent.displayName = `ReduxFormMaterialUI${MaterialUIComponent.name}`
      return InputComponent
    }

    const mapError = ({ meta: { touched, error, warning } = {}, input: { ...inputProps }, ...props }, errorProp = 'errorText') =>
      touched && (error || warning) ? { ...props, ...inputProps, [errorProp]: error || warning } : { ...inputProps, ...props }

    export default createComponent(
      SuperSelectField,
      ({ input: { onChange,value, onBlur, ...inputProps }, onChange:onChangeFromField, ...props }) => ({
        ...mapError(props),
        ...inputProps,
        value: value,
        onChange: (event, index, value) => {
          onChange(value)
          if(onChangeFromField) {
            onChangeFromField(value)
          }
        },
        onBlur: () => onBlur(value)
      }))
`

And i get the next error:
<img width="870" alt="screen shot 2017-03-19 at 4 30 43 pm" src="https://cloud.githubusercontent.com/assets/782464/24085427/8c90610c-0cc1-11e7-8256-ea8e2303460e.png">

**Comment by pfortes** [comment]
Never mind, i made it work!

To get rid of the error I just had to set an initial value for the field (an empty list) 

And i had to modify the onChange event handler from my wrapper to follow the format onChange(selectedValues, name)

**Comment by Sharlaan** [comment]
Glad you managed your use case.

**Comment by TarikHuber** [comment]
@pfortes do you have a working example of your solution?

**Comment by pfortes** [comment]
@TarikHuber i use the following aproach:

in the file SuperSelectFieldWrapper.js i have:
```
 import SuperSelectField from 'material-ui-superselectfield'
    import { Component, createElement } from 'react'

    /**
     * Creates a component class that renders the given Material UI component
     *
     * @param MaterialUIComponent The material ui component to render
     * @param mapProps A mapping of props provided by redux-form to the props the Material UI
     * component needs
     */
    function createComponent(MaterialUIComponent, mapProps) {
      class InputComponent extends Component {
        getRenderedComponent() {
          return this.refs.component
        }

        render() {
          return createElement(MaterialUIComponent, {
            ...mapProps(this.props),
            ref: 'component'
          })
        }
      }
      InputComponent.displayName = `ReduxFormMaterialUI${MaterialUIComponent.name}`
      return InputComponent
    }

    const mapError = ({ meta: { touched, error, warning } = {}, input: { ...inputProps }, ...props }, errorProp = 'errorText') =>
      touched && (error || warning) ? { ...props, ...inputProps, [errorProp]: error || warning } : { ...inputProps, ...props }


    export default createComponent(
      SuperSelectField,
      ({ input: { onChange,value, onBlur, ...inputProps }, onChange:onChangeFromField, ...props }) => ({
        ...mapError(props),
        ...inputProps,
        value: value,
        //onChange: (event, index, value) => {
        onChange: (value,name) => {
          onChange(value)
          if(onChangeFromField) {
            onChangeFromField(value)
          }
        },
        onBlur: () => onBlur(value),
        style: { minWidth: 150, display: 'block', width: '100%', maxWidth: 250, margin: '20px 0', color:'#009999'}
      }))
```

and then i use it like:
```
import { Field, reduxForm, getFormValues } from 'redux-form'
              
 import SuperSelectFieldWrapper from '../components/SuperSelectFieldWrapper'
              
<Field name='Accesosrios__c'
                  component={SuperSelectFieldWrapper}
                  multiple
                  hintText='Accesorios'
                  className='superSelect'>
                    {this.props.accesorios.map((val, i) => {
                      return (
                        <div key={'acc_'+i} value={val}>{val}</div>
                      )
                    })}
                  </Field>
```

And wrap my class with redux form: 

`export default reduxForm({
  form: 'formaVenta',
  initialValues: {}
})(FormaVenta)`

**Comment by Sharlaan** [comment]
@pfortes Can you provide a minimalist and documented example please ?

To be honest, it's unreadable.

**Comment by TarikHuber** [comment]
@Sharlaan o no it's fine :) the most part comes from the redux-form material-ui project. I wonder why they don't export the  createComponent and mapError.
@pfortes thank you :) I got it running couple of minutes after the question. The small part with the onChange event made the problems. Forgot about it after visiting this issue.

If someone needs a running solution in a project you can find one here: https://github.com/TarikHuber/react-most-wanted

**Comment by pfortes** [comment]
@TarikHuber Glad you got it working!

**Comment by zomars** [comment]
I'm having the same issue, but only when trying to use the `multiple` attribute. Has anyone tried this before?
