### ISSUE TITLE
How to style the autocomplete?

### ISSUE THREAD

**Issue by EmilioHerreraSoukup** [Sharlaan/material-ui-superselectfield#26]
How can I style the autocomplete "search bar"?

**Comment by Sharlaan** [comment]
You can't for now.

I'll try to add a prop `underlineColor`|

**Comment by Sharlaan** [comment]
Sorry for late answer, if you still interested can you check your usecase with latest version featuring props `underlineStyle` and `underlineFocusStyle` please ?
