### ISSUE TITLE
Error in CodeExample3 with "Raphaël"

### ISSUE THREAD

**Issue by TarikHuber** [Sharlaan/material-ui-superselectfield#29]
In the CodeExample3 if you select Raphaël and others and the go back to the SuperSelectField Raphaël is not marked in the `menu` as selected but still apearing in the selectedRednerer.

You can't remove him after you selected him once and you are able to add him multiple times.

**Comment by Sharlaan** [comment]
Bug confirmed, thanks 👍

**Comment by Sharlaan** [comment]
Fixed
