### ISSUE TITLE
How do I install

### ISSUE THREAD

**Issue by joadr** [Sharlaan/material-ui-superselectfield#3]
Hello!,
I've loved it!, how do I install it? I didn't see it on npm. Are you planning to do that soon?

;)

**Comment by Sharlaan** [comment]
Thanks for your interest !

Actually i'm still learning how to make it a package.
In the meantime, you can :
- drop superSelectField.js and SelectionsPresenter.js in some common components directory
- import superSelectField into your page
- study CodeExample1 how to manage data in state (you can even do it with Redux)

You can also post issues if you find any, i'll try to fix them when i can.

**Comment by Sharlaan** [comment]
Update: now you should be able to npm install

Please report if anything goes wrong, thanks.
