### ISSUE TITLE
Use the correct basename on the demo website.

### ISSUE THREAD

**Issue by ChrisJamesC** [Sharlaan/material-ui-superselectfield#31]
When on a particular example, the URL displayed in the browser is https://sharlaan.github.io/example1 when it should be https://sharlaan.github.io/material-ui-superselectfield/example1. 

For example, in react router, it's solved using [`basename`](https://reacttraining.com/react-router/web/api/BrowserRouter/basename-string)

This issue makes sharing examples harder.

**Comment by Sharlaan** [comment]
Hello, thanks for the report.

I just deployed my current WIP with basename='/material-ui-superselectfield', but the poblem persists.... i think it maybe related to github hosting... i don't know :s

**Comment by ChrisJamesC** [comment]
Probably yes. I don't know if there is a setting possible for html5 navigation on github pages. 
You could try to use [HashHistory](https://reacttraining.com/react-router/web/api/HashRouter) instead of BrowserHistory. It's designed exactly for this use case.

**Comment by Sharlaan** [comment]
ok i now deployed with HashRouter, it should works with:
[https://sharlaan.github.io/material-ui-superselectfield/#/example1](https://sharlaan.github.io/material-ui-superselectfield/#/example1)

**Comment by ChrisJamesC** [comment]
Awesome thanks!
