### ISSUE TITLE
package.json points to non existent superSelectField.js (case sensitive)

### ISSUE THREAD

**Issue by mrbarletta** [Sharlaan/material-ui-superselectfield#4]
Hi there nice piece of work! keep at it :)

`npm install `  is failing due to  
```
material-ui-superselectfield@1.0.0 prepublish: `babel src/superSelectField.js -o lib/superSelectField.js`
```
your repo has the file but it starts with an upperCase.

**Comment by Sharlaan** [comment]
Hi thanks for the report !

I just pushed a modified lib/SuperSelectField.js and package.json
please tell e if that installs correctly ?

**Comment by mrbarletta** [comment]
Great! - it is solved thanks!
