### ISSUE TITLE
Styling issue

### ISSUE THREAD

**Issue by tkostus** [Sharlaan/material-ui-superselectfield#40]
Hello

great work with this component! 

I incorporated SuperSelectField into my project and noticed few quirks:

- blue border, font not matching the rest of MUI components:
![enabled](https://user-images.githubusercontent.com/9673785/27406292-56b6c6d4-56cc-11e7-9bcd-fd8c6e64117a.gif)
- still selectable when disabled:
![disabled](https://user-images.githubusercontent.com/9673785/27406324-6739c9d4-56cc-11e7-9136-45cd8c2013bc.gif)

To make sure this has nothing to do with my setup i spun up an empty create-react-app project and created above recordings. Am I missing something obvious?

**Comment by Sharlaan** [comment]
Hello
Add a "css reset" in your main .css file:
`*:focus { outline: none; }`

**Comment by tkostus** [comment]
@Sharlaan thanks for a quick reply!

So the outline is gone, what about the other issues - any ideas? Why does it not inherit styles from main material package? Something to do with create-react-app?

**Comment by tkostus** [comment]
This is what I'm looking at (disabled prop is set to true but i can still select the field, font is not Roboto, underline is different than on regular SelectField):
![image](https://user-images.githubusercontent.com/9673785/27422031-ad65f5ec-5724-11e7-9d55-6555324dd568.png)

**Comment by nitupune** [comment]
Hi, Please help me  have implemented multi select in my web APP,  facing some styling issue like , It works fine but when I am start typing in filter text box it appends Vertical and Horizontal scroll-bar,

**Comment by Sharlaan** [comment]
@ nitupune please don't pollute tkostus thread with a different issue, open your own.

@tkostus : i just commited a version fixing underLine misalignment and shouldnot get focused color when disabled=true. it is in lib/ folder here in this repo, please tell me if it fixes your issues.

**Comment by tkostus** [comment]
@Sharlaan many thanks - I have actually figured this out since and made some other tweaks to make it practically undistinguishable from the original SelectField:
![28a1dc94-a951-4455-9ea9-56170ac59d1f](https://user-images.githubusercontent.com/9673785/29485959-a4f632fa-84d3-11e7-8a19-321a69abaab8.gif)
I've forked your repo and made the tweaks there, mostly in SelectionPresenter - feel free to review and include in your code. It's not very scientific so I'm not proposing a PR :)
