### ISSUE TITLE
Can we open popover on the top of textbox when not enough space at the bottom side 

### ISSUE THREAD

**Issue by nitupune** [Sharlaan/material-ui-superselectfield#41]
I am using supperselectfield inside the table row I am facing problem at the last row when opening drop-down it get hidden behind of my container. same if I check Material UI select it get open at the top when not enough space at the bottom side can we implement same here.

**Comment by nitupune** [comment]
Any Suggestions.. ?

**Comment by nitupune** [comment]
Hi,

I observed that, "canAutoPosition" property of Popover is set to false, because of which popover is not being positioned on top.

can you expose this property?

**Comment by Sharlaan** [comment]
Can you tell me if the version on branch fix/#41-canAutoPosition works for you ?

**Comment by Sharlaan** [comment]
Can you tell me if the version1.5.6 works for you ?

**Comment by nitupune** [comment]
Hey, thanks for the fix. It's working
