### ISSUE TITLE
Doesn't work in Internet Explorer 11 & Firefox

### ISSUE THREAD

**Issue by wittyPuneet** [Sharlaan/material-ui-superselectfield#44]
There seems to styling issues with Internet Explorer 11 and Firefox. On Chrome it seems to work just fine.

**Firefox:**
1) The underline is pushed to the right.

**Internet Explorer 11**
1) The underline is pushed to the right, and 
2) Clicking on the drop down doesn't show the list of items.

**Firefox Preview:**
![image](https://user-images.githubusercontent.com/28158605/29121142-f209f3de-7d2a-11e7-8853-e87b090273b5.png)

**Internet Explorer Preview:**
![ie superselect field](https://user-images.githubusercontent.com/28158605/29121123-dfa34a4c-7d2a-11e7-87c8-0cb8e03523c7.png)

**Comment by Sharlaan** [comment]
underLine should be fixed with latest commit

on other hand, what error IE11 tells you when clicking ? (lol IE....)

**Comment by wittyPuneet** [comment]
The underline issues seems to be fixed in both IE and Firefox. IE11 issue seems to be happening because it lacks support for 'includes' function. The solution would be to either replace it with `indexOf(string) >=0` or to bypass the inbuilt filtering with a custom filter using the autocompleteFilter property.

**Comment by Sharlaan** [comment]
Can you try the version in branch:  
 fix/#44-IE11-includesPolyfill

Note: the quirks in CodeExample1 are actually bugs from IE11 with flexbox, i don't want to deal with.

**Comment by wittyPuneet** [comment]
Works great now. Thanks.
