### ISSUE TITLE
OnChange attribute remove selectedItems 

### ISSUE THREAD

**Issue by reemyrail** [Sharlaan/material-ui-superselectfield#45]
Whenever I specify the onChange parameter the selected value isn't displayed in the SelectionsPresenter
`<SuperSelectField
          name='state31'
          floatingLabel='اختر بلد'
          onChange={(selectedValues,name) => {this.props.checkValid(selectedValues , name)}}
          hintText=''
          elementHeight={58}
          style={{ width: 300, marginTop: 20, marginRight: 40 }}
        >`
By removing the onChange everything goes back to normal...
Any Ideas?

**Comment by Sharlaan** [comment]
For reproductibility, can you make a code example in [CodeSandbox.io](https://codesandbox.io) please ?
