### ISSUE TITLE
Material UI moved some components

### ISSUE THREAD

**Issue by OozoraHaruto** [Sharlaan/material-ui-superselectfield#50]
Hi this is my first time using this and I encountered a few issues where the module cannot be found and I couldn't continue... So I decided to try and find the correct modules in material-ui directory. I have yet to test all as I said I am using it for the first time.

Previous
`var _Popover = require('material-ui/Popover/Popover');`
New
`var _Popover = require('material-ui/internal/Popover');`

Previous
`var _checkBoxOutlineBlank = require('material-ui/svg-icons/toggle/check-box-outline-blank');`
New
`var _checkBoxOutlineBlank = require('material-ui/svg-icons/check-box-outline-blank');`

Not quite sure:
Previous
`var _arrowDropDown = require('material-ui/svg-icons/navigation/arrow-drop-down');`
New
`var _arrowDropDown = require('material-ui/svg-icons/arrow-downward');`

Previous
`var _check = require('material-ui/svg-icons/navigation/check');`
New
`var _check = require('material-ui/svg-icons/check-box');`

Hope you will update to support the newest material-ui... I realise they are updating their directories frequently which is causing alot of issues with other repos.

Best Regards

**Comment by Sharlaan** [comment]
which material-ui are you using ?
i just released a version compatible with v0.19

**Comment by OozoraHaruto** [comment]
"material-ui": "^1.0.0-beta.5",
"material-ui-superselectfield": "^1.5.5",
"webpack": "^2.6.1"

adding in webpack incase it affects the result

**Comment by Sharlaan** [comment]
"material-ui": "^1.0.0-beta.5"

=> check my package.json: it clearly states this is incompatible with M-UI v1+

**Comment by OozoraHaruto** [comment]
You don't intend to update it to support v1?? Abit wasted but I understand... thanks

**Comment by Sharlaan** [comment]
I'll do when they'll be in stable state, not before.

Since early 2015 they are frequently evolving the v1, so i chose the stable v0.x to base my component on.

**Comment by OozoraHaruto** [comment]
Hope it's soon since it's already beta 5... your repo seems really fun to use, thinking of how to use it redux form 😄
