### ISSUE TITLE
Passing properties to menu wrapper

### ISSUE THREAD

**Issue by robhadfield** [Sharlaan/material-ui-superselectfield#52]
Is there a way to pass properties (classname / id etc) to the menu wrapper? I can pass styles to the menu directly but these don't affect the outer container.

I'm trying to work around the issue with the dropdown hanging off the screen.

Any help appreciated! :)
Rob

**Comment by Sharlaan** [comment]
Please try v1.5.6 then close this issue (or report any problem).

**Comment by robhadfield** [comment]
@Sharlaan - any idea on this one? It would be great to be able to add a className to the menu itself.

**Comment by Sharlaan** [comment]
Did you try 1.5.6 ? this version with canAutoPosition should solve this issue with offscreen dropdown

**Comment by robhadfield** [comment]
I'm testing that at the moment in the other thread - I'm just asking about className and ID here :)

**Comment by Sharlaan** [comment]
There is `menuStyle` but good idea about some `menuProps` properties applied to the inner Popover.
