### ISSUE TITLE
Can't resolve babel-polyfill

### ISSUE THREAD

**Issue by samhh** [Sharlaan/material-ui-superselectfield#55]
Issue only present in `1.5.6`. `1.5.5` is fine.

```
ERROR in ./node_modules/material-ui-superselectfield/lib/SuperSelectField.js
Module not found: Error: Can't resolve 'babel-polyfill' in '[path]/node_modules/material-ui-superselectfield/lib'
@ ./node_modules/material-ui-superselectfield/lib/SuperSelectField.js 21:0-25
[rest of stacktrace in my project]
webpack: Failed to compile.
```

**Comment by MaximilianPichler** [comment]
Are you sure you have the babel-polyfill npm package installed?

`npm install babel-polyfill`

**Comment by samhh** [comment]
I don't (targeting modern browsers with my Babel config so it's unneeded), but I also don't see that listed in the README as a dependency? And if it is... isn't that a pretty bloated dependency to have?

**Comment by Sharlaan** [comment]
I included babel-polyfill recently to resolve issues with IE11 (issue #44)
i included it in dev-dependencies to avoid bloating the lib and it seemed to resolve the issue....

If you have a better idea to add support for IE11, i'm open (better than saying "no support")

**Comment by samhh** [comment]
Could you not rely on the end user to include it? i.e. if you target modern browsers you can leave it, if you target older browsers you'll need to include that or otherwise polyfill the environment.

Also if it's only `includes` that's missing that should be only a few lines to manually polyfill iirc.

**Comment by Sharlaan** [comment]
indeed i thought of just replacing includes with indexOf but then got errors with .find() then with another ES6 method, and so on...

I target definitely modern browsers, but IE11 seems to be still largely used...
Problem is i'm using create-react-app, which is polyfilling only the demos site, not the lib. That's why i added a script in package.json for just polyfilling the lib.

How would you cover both of these aspects?

**Comment by samhh** [comment]
Wouldn't the solution be to transpile the module with Babel before you ship it? Yes, it's unideal to have transpiled/dist files in your repo, but that has to beat having Babel effectively forced as a dependency on the user's side.

**Comment by Sharlaan** [comment]
Thing is it's what i were doing since quite some time:
`"buildLib": "babel src/SuperSelectField.js -o lib/SuperSelectField.js"`

But apparently this issue#44 made me realize babel didnot transpile properly unless added babel-polyfil....

**Comment by samhh** [comment]
Hmm... what do other modules out there do? Surely they're not all restricting themselves to ES5/a subset of ES6+?

**Comment by kcjl519** [comment]
babel-polyfill is actually part of babel-node cli, so if you require it as part of your lib, it will give an error as such ```babel-polyfill - error Error: only one instance of babel-polyfill is allowed```. I think it should be up to the application that is trying to use the lib, to do the babel-polyfill (for the entire application), in terms of developing the lib, you can simply add babel-polyfill into webpack-dev-server.config as part of the entry like such.

```
  entry: {
    main: [
      // only- means to only hot reload for successful updates
      'webpack/hot/only-dev-server',
      'babel-polyfill',
      './main.js'
    ]
  },
```

It's actually really hard to use the lib in another environment where they are also running the babel-polyfill, I've had to fork this and remove it.

**Comment by Sharlaan** [comment]
ok i think this issue is solved by latest releases.
