### ISSUE TITLE
Can't set open field by default.

### ISSUE THREAD

**Issue by Seyi-Keye** [Sharlaan/material-ui-superselectfield#57]
There is no option to set the SuperSelect open field by default. (there seems to be no option for that in the props)
Say like so
```<SupserSelect isOpen={true | false }/>```

 it seems to trigger closing the menu on click of empty space. Is this a known issue or I'm getting something wrong. ready to submit a PR for this if this is an issue

**Comment by nitupune** [comment]
I am looking for the same feature;
but it will be great if there is any property e.g. openOnFocus={true/false} so that the dropdown will open whenever the user comes to SelectField through tabbing

**Comment by MaximilianPichler** [comment]
Hey!
I've implemented an option to open the field by default.
You can check out the fork [here](https://github.com/MaximilianPichler/material-ui-selectfield).
(The demo contains an example of the always open feature)

**Comment by Sharlaan** [comment]
v1.6.0 is out!
it includes `openImmediately` property check it out in documentation
