### ISSUE TITLE
Is possible to customize the message 'No match found' on autocomplete?

### ISSUE THREAD

**Issue by filipenevola** [Sharlaan/material-ui-superselectfield#6]
Hello, I looked into the code and I couldn't find a way to customize the message 'No match found'.

Is that possible? If it is not possible, can I submit a PR for that?

I'm from Brazil and my app is target to Brazilians then I need to use Portuguese in every message.

Thanks.

**Comment by Sharlaan** [comment]
No need for a PR: i just pushed your wish !

Enjoy :p

**Comment by filipenevola** [comment]
@Sharlaan that was fast, thank you :)

Did you publish to npm? I saw your code here but looks that is not on npm yet.

**Comment by Sharlaan** [comment]
Indeed, not published, feel free to use directly SuperSelectField.js

I'm planning a v1 release, so need to be clean.

**Comment by filipenevola** [comment]
It worked. :) 

I saw that you published a new version to npm but here it is 1.0.0 and there is 1.1.0. Did you do that on purpose?

**Comment by Sharlaan** [comment]
Yes, i kinda mixed semver versions with new props.

I'm happy to see it works for you, enjoy !
