### ISSUE TITLE
Autocomplete field is not created with React 16

### ISSUE THREAD

**Issue by hammelion** [Sharlaan/material-ui-superselectfield#63]
On focus an error occurs here:
var input = (0, _reactDom.findDOMNode)(this.searchTextField).getElementsByTagName('input')[0];

Debugger shows that this.searchTextField is undefined.

**Comment by TarikHuber** [comment]
Hey,

Chek out material-ui-selectfield It is a comolet refactored fork of this project. With all bugfixes implemented and published. We made it because we also use react 16 in production and need this functionality. I hope it helps.

**Comment by hammelion** [comment]
Thanks! I'll give it a try!

**Comment by hammelion** [comment]
https://www.npmjs.com/package/material-ui-selectfield works like a charm, thank you again!

**Comment by Sharlaan** [comment]
Just released v1.6.0 including important bug fixes.
Please tell me if this version solves your issue.
