### ISSUE TITLE
errorText property not working.

### ISSUE THREAD

**Issue by manishk-sdei** [Sharlaan/material-ui-superselectfield#65]
<SuperSelectField
        showAutocompleteThreshold={1}
        useLayerForClickAway={true}
        hintText=''
        errorText={touched && error}
        floatingLabel={label}
        value={selectedObj || 1}
        nb2show={10}
        onChange={ (e, name) => changeSelectedObj(e, name)}
        style={{ minWidth: 200, margin: 10, paddingTop:30 }}
        hoverColor='rgba(3, 169, 244, 0.15)'
        menuCloseButton={<RadioButton label='close' hoverColor={'lightSalmon'} />}
      >
        { options ? optionsList : ''}

      </SuperSelectField>

**Comment by MaximilianPichler** [comment]
This is a known issue. I have added Error Text and a few more things over on my fork: https://github.com/MaximilianPichler/material-ui-selectfield

**Comment by manishk-sdei** [comment]
'errorText' is available in material-ui-selectfield not in 'material-ui-SuperSelectField'. 
Suggest me how to add error message in SuperSelectField ?

**Comment by MaximilianPichler** [comment]
You could Just swap material-ui-superselectfield with material-ui-selectfield. They are fully compatible.

**Comment by manishk-sdei** [comment]
@MaximilianPichler Man you saved my day. Thanks a lot.

**Comment by Sharlaan** [comment]
Just released v1.6.0 including this feature, please check it.
