### ISSUE TITLE
onChange is not getting Triggers when selecting/unselecting an option.

### ISSUE THREAD

**Issue by shivwork** [Sharlaan/material-ui-superselectfield#66]
Trying to make MultiSelction AutoComplete tag field. Exactly like Example 3. Got stuck in onRequestDelete.        

<MaterialSelectField
          showAutocompleteThreshold={1}
          hintText=''
          multiple={true}
          checkPosition="left"
          errorText={touched && error}
          floatingLabel={label}
          value={selectedArr}
          children={selectedArr}
          nb2show={7}
          onChange={(selected, name) => handleOnChange(selected, name)}
          required={true}
          style={{ minWidth: 200, margin: 10, paddingTop: 30 }}
          selectionsRenderer = {handleCustomDisplaySelections}
      >
        { optionsList }
      </MaterialSelectField>

let selectedArr = [];
  const handleRequestDelete = (key, items) => (e) => {  
    var newArr = selectedArr.slice(0);
    newArr.splice(key, 1);
    selectedArr = newArr.slice(0);
  };

  const handleCustomDisplaySelections = (item, values) => {
    return <div>
      {selectedArr.length ?
          <div>
            <div style={{ display: 'flex', flexWrap: 'wrap' }}>
              {selectedArr.map(({ label, value: value }, index) =>
                  <Chip key={index} style={{ margin: 5 }} onRequestDelete={handleRequestDelete(index, selectedArr)}>
                    {label}
                  </Chip>
              )}
            </div>
          </div>
          : ''
      }
    </div>;
  };

**Comment by MaximilianPichler** [comment]
Hey check out version 1.0.17 of my fork: https://github.com/MaximilianPichler/material-ui-selectfield
I've fixed the problem so that onChange gets called when an element gets selected/unselected

**Comment by shivwork** [comment]
I am using  material-ui-selectfield. Still onChange not working as expected.  
This is My code:
<MaterialSelectField
      showAutocompleteThreshold={1}
      hintText=''
      errorText={touched && error}
      floatingLabel={label}
      value={selectedObj}
      nb2show={7}
      name="role"
      required={true}
      dropDownMenuProps={{ animated: false }}
      onChange={ (e) => changeSelectedObj(e)}
      style={{ minWidth: 200, margin: 10, paddingTop: 30 }}
      hoverColor='rgba(3, 169, 244, 0.15)'
      menuCloseButton={<RadioButton label='close' hoverColor={'lightSalmon'} />}
    >
      { optionsList }
    </MaterialSelectField>

**Comment by shivwork** [comment]
Want to create Multiselect field. Exactly like example-3. When i delete tag, selected item not getting removed from selected values and menu dropdown. 
![image 1](https://user-images.githubusercontent.com/27669700/31327217-6ee8c03e-aceb-11e7-916d-4625601fbfe1.jpg)

**Comment by MaximilianPichler** [comment]
Hey! Check out the Chip-selection demo: https://maximilianpichler.github.io/material-ui-selectfield/
OnChange and remove from selected values are both working fine

**Comment by Sharlaan** [comment]
Just released v1.6.0 including important bug fixes.
Please tell me if this version solves your issue.
