### ISSUE TITLE
Keyboard enter not working on dropdown item.

### ISSUE THREAD

**Issue by shivwork** [Sharlaan/material-ui-superselectfield#68]
value not getting select using keyboard enter. Its works fine using mouse click.

**Comment by Sharlaan** [comment]
Just released v1.6.0 including important bug fixes.
Please tell me if this version solves your issue.

**Comment by shivwork** [comment]
Still not working. 
I am facing two problems 
Keyboard selection and floatingLabel not working properly in SingleSelect.

**Comment by Sharlaan** [comment]
Can you tell me if the "Basic" example in Demo page works for you regarding keyboard selection please ?  If not, which browser do you use ?

Regarding floatingLabel, i reproduced your particular case and fixing it at the moment.

**Comment by shivwork** [comment]
keyboard selection not working in any case. I am using browser chrome.
Regarding floatingLabel, Its works perfect for MultiSelection. But in SingleSelection, By default floatingLabel position moves up, when i select any item from dropdown, then its works as usual.

**Comment by Sharlaan** [comment]
For floatingLabel, i know: selectionsPresenter doesnot use same container for multiSeelction mode than for single selection mode. The logic for the single selection mode is failing.

On other hand, i would like to resolve your issue with keyboard selection, it's working in all my test environnements... i'm using latest versions of Chrome Firefox Edge and IE11 on Windows10 and latest NodeJS.
i deployed v1.6.0 2 days ago on the Demo page wich includes bug fixes for keyboard.
There is a slight bug since you have to double keypress just after the menu opened. (related to focus, i need some help on that topic...) but it should definitely work.

**Comment by shivwork** [comment]
As of now, It is very necessary to fix  floatingLabel bug.
This is my code.
  <MaterialSelectField
      showAutocompleteThreshold={1}
      errorText={touched && error}
      floatingLabel={label}
      value={selectedObj}
      nb2show={7}
      anchorOrigin={{ vertical: 'top', horizontal: 'left' }}
      required={true}
      onChange={(e) => changeSelectedObj(e)}
      hoverColor='rgba(3, 169, 244, 0.15)'
    >
      {optionsList}
    </MaterialSelectField>

**Comment by shivwork** [comment]
@Sharlaan when can i expect, the floatingLabel in singleSelection  bug will fix ?

**Comment by Sharlaan** [comment]
Can you try v1.6.1 released yesterday and tell me if it solves both your issues ? please.

**Comment by shivwork** [comment]
No. Its not working.

**Comment by Sharlaan** [comment]
more details please. with code, and last version.

**Comment by shivwork** [comment]
"material-ui-superselectfield": "^1.6.1".

<SuperSelectField
      showAutocompleteThreshold={1}
      errorText={touched && error}
      floatingLabel={label}
      hintText=''
      value={selectedObj}
      nb2show={7}
      anchorOrigin={{ vertical: 'top', horizontal: 'left' }}
      required={true}
      onChange={(e) => changeSelectedObj(e)}
      hoverColor='rgba(3, 169, 244, 0.15)'
    >
      {optionsList}
    </SuperSelectField>

**Comment by shivwork** [comment]
For testing, I am using your code. 
   <SuperSelectField
      name='floatingLabelState'
      floatingLabel='Floating label'
      hintText={false}
      value={selectedObj}
      style={{ minWidth: 150, margin: 10 }}
    >
      <div value='A'>Option A</div>
      <div value='B'>Option B</div>
      <div value='C'>Option C</div>
    </SuperSelectField>

Why hintText shows  'Click me', but hintText is not there in your Basic demo.
