### ISSUE TITLE
Your project is not working.

### ISSUE THREAD

**Issue by dlape** [Sharlaan/material-ui-superselectfield#69]

**Comment by TarikHuber** [comment]
![unbenannt](https://user-images.githubusercontent.com/11230962/31486277-36a4654a-af37-11e7-9809-7e879d657110.PNG)

**Comment by dlape** [comment]
whats wrong with you people nowadays?.
  I just want to learn programming even though I am still in my 6th grade
  but recently someone making fun of me and acting like a cool tosser.
  Instead of the effort to make fun of someone why not teach him the right way to do things.
  I really look up people who do apps, games, website but if all programmers are like this
  then all of you is a trash.

**Comment by TarikHuber** [comment]
Hi @dlape,  
it is great that you try to code with your age. Respect for that! When you gain experience and create your own Github projects and libraries you will understand my reaction. You should learn a little bit more on how to write issues before sending some. People who are working on this kind of projects can't read you mind to see what is wrong with your code. So I would recomment that you read this [instructions ](https://wiredcraft.com/blog/how-we-write-our-github-issues/)for github issues and send another one after that. An issue with the title "**Your project is not working**" would be funny no mater how old you are or who you are at all. We can't see that so don't take it personal.

**Comment by Sharlaan** [comment]
Closing, nothing constructive here, and such behavior dirties open source's mind.

Learn yourself, mount your own projectS, then maybe you will understand how developpers help each other.

**Comment by TarikHuber** [comment]
You helped him alot with closing this issue

**Comment by Sharlaan** [comment]
he should still have a notification of our answers (especially your link 👍 ).

On other hand, as long nothing constructive is posted, this thread has no reason to stay open.
