### ISSUE TITLE
How to disable the field

### ISSUE THREAD

**Issue by gyarasu** [Sharlaan/material-ui-superselectfield#7]
Hi.

I'm trying to use your great component.
I want to switch the state of the field (enable or disable).
Is it possible to disable the field?

Please check below.
I would like to set "disabled" prop.
```
        <SuperSelectField
          name='state1'
          hintText='Single value'
          onChange={this.handleSelection}
          value={state1}
          style={{ minWidth: 150, marginRight: 40 }}
          disabled={true}
        >
          <div value='A'>Option A</div>
          <div value='B'>Option B</div>
          <div value='C'>Option C</div>
        </SuperSelectField>
```

Thanks.

**Comment by Sharlaan** [comment]
Hello, thanks for the suggestion.

It isnot supported yet, i added it to my TODO list.
Hopefully this prop will be available with the final v1 release.

**Comment by Sharlaan** [comment]
new v1.1 now includes disabled prop.

Have fun !

**Comment by gyarasu** [comment]
I got it!
Thanks for your rapid modification!
