### ISSUE TITLE
Missing property "className"

### ISSUE THREAD

**Issue by FDiskas** [Sharlaan/material-ui-superselectfield#72]
It should be possible to add a class name to superselectfield. This needed to hack inlined styles with `!important` flag.

**Comment by Sharlaan** [comment]
1. having to rely on !important means a bigger problem in your CSS rules. That's what i'm trying to avoid with proposing a flexible enough omponent.

2. The documentation has a "Styling properties" almost 2 pages long paragraph, so please can you be more explicit on your CSS problem and i'll try to help or eventually validate your request and implement something.

**Comment by FDiskas** [comment]
```
import SelectField from 'material-ui-superselectfield';

getElements() {
        const { items } = this.props;
        return this.props.items.reduce((nodes, { value, label, disabled }) => {
            return [...nodes, <div key={value} value={value} label={label} disabled={disabled}>{label}</div>];
        }, []);
    }

    render() {
        return (
                <SelectField
                    className={'demo'}
                >
                    {this.getElements}
                </SelectField>
        );
    }
```
And this "demo" class is missing in component. :exclamation:

**Comment by Sharlaan** [comment]
1. [off-topic]
- why deconstruct this.props.items then use this.props.items right below ?
- why do you use reduce() without any condition ? reduce = map+filter, a map() should be enough ?

2. Please read Documentation, you can style directly with the style property. Make your 'demo' class into a JS object then deconstruct it in style={{...demo}}. Check also CodeExamples on how styling is used.

3. which style property(ies) are you missing to the point of relying to !important ? Maybe you are correct and needs an additional styling prop.

**Comment by FDiskas** [comment]
1. I cut out some additional code.
2. Thanks

**Comment by p-funky** [comment]
Hi @Sharlaan 
I know this is closed but I personally had a minor use case here where I wanted to pop up the options menu of the superselectfield by clicking an icon beside it. I intend to use jquery here and it would be a lot easier to just target the className.
