### ISSUE TITLE
Add reset ability (select none)

### ISSUE THREAD

**Issue by FDiskas** [Sharlaan/material-ui-superselectfield#74]
In some cases needs to reset selected multi select list, or reset the already selected item in single select mode. This could be done by allowing to add a footer to drop down or adding an item with value `null` or `undefined`
example:
![vytenis kuciauskas-20171017130632-270x201](https://user-images.githubusercontent.com/468006/31659219-082b6552-b33c-11e7-8ac0-75eadc1acbc6.png)

**Comment by Sharlaan** [comment]
in single selection mode, just reclick on the selected option...

But for multiple mode, this is  planned feature along "select all".
no ETA sorry

**Comment by FDiskas** [comment]
Yes I know that it's posible to do so by reclicking on selected item, but for end user it's not so clear. :arrow_double_down:

**Comment by shivwork** [comment]
![reselectitems](https://user-images.githubusercontent.com/27669700/32167417-ccd9cc34-bd8e-11e7-84c5-ef6a861b54ef.jpg)
@FDiskas Can you show me your code ? I am also working on it, but in different way.

**Comment by FDiskas** [comment]
In that screenshot is a simple selectfield of material-ui :full_moon_with_face:
```js
import React from 'react';
import PropTypes from 'prop-types';
import { MenuItem, SelectField } from 'material-ui';

const DropDown = (props) => {
    const { withReset, items, ...rest } = props;

    return (
        <SelectField
            {...rest}
        >
            {withReset && <MenuItem secondaryText={'Select none'} value={undefined} primaryText="" style={{ color: 'silver' }} />}
            {items.map(item => <MenuItem key={item.value} value={item.value} primaryText={item.label} />)}
        </SelectField>
    );
};

DropDown.propTypes = {
    withReset: PropTypes.bool,
    items: PropTypes.arrayOf(PropTypes.shape({
        value: PropTypes.any,
        label: PropTypes.string,
    })).isRequired,
};
DropDown.defaultProps = {
    withReset: false,
    items: [],
};

export default DropDown;
```

**Comment by shivwork** [comment]
FloatingLabel not working correctly in SingleSelect. ByDefault label stay at top. when field get dirty, then works as expected. Please Help me.
Ui : 
![singleselect](https://user-images.githubusercontent.com/27669700/32271397-af60ff32-bf1f-11e7-8181-ede47bcbce92.jpg)

Code : 
 <MaterialSelectField
      disabled={disabled ? disabled : false}
      showAutocompleteThreshold={1}
      errorText={touched && error}
      floatingLabel={label}
      value={selectedObj}
      nb2show={7}
      anchorOrigin={{ vertical: 'top', horizontal: 'left' }}
      required={true}
      onChange={(e) => changeSelectedObj(e)}
      hoverColor='rgba(3, 169, 244, 0.15)'
    >
      {optionsList}
    </MaterialSelectField>
