### ISSUE TITLE
Multiselect - missing property to sort by selected items

### ISSUE THREAD

**Issue by FDiskas** [Sharlaan/material-ui-superselectfield#75]
If the list is very big, for the UX - selected items should be placed at the top of the list - I mean sorted by selection.
![vytenis kuciauskas-20171017131832-218x306](https://user-images.githubusercontent.com/468006/31659721-b761ebbc-b33d-11e7-9e97-9d94c9b4118f.png)

**Comment by Sharlaan** [comment]
Nice one! thanks

**Comment by Sharlaan** [comment]
After some thoughts and by common agreeness with other contributors, we think this should not be the responsibility of the component to manipulate data.
SelectField is just a presenting component.
I'm aware this is kinda borderline, but this request **should be done on the developper side**.
You can set the sorted array as source, superSelectField will automatically detect if children changed -by sorting- and will rerender.

**Comment by FDiskas** [comment]
:pear:
