### ISSUE TITLE
Autocomplete not showing up

### ISSUE THREAD

**Issue by tonysam** [Sharlaan/material-ui-superselectfield#77]
The autocomplete field is not showing up for me. How can I enable the autocomplete feature?
I am using React 15.6.1

**Comment by Sharlaan** [comment]
In documentation, did you check `showAutocompleteThreshold` ?

I still does not work, please give more details (code?)

**Comment by tonysam** [comment]
It still doesn't work for me. I have given showAutoCompleteThreshold as the count of options in the select field.
Here is my code: 

<SuperSelectField
          		id="super-select"
          		name="country"
          		checkPosition='left'
          		elementHeight={50}
		        className="each-input pull-left super-select"
		        hintText="Immigrant Country"
		        required
		        hintTextAutocomplete="Type here.."
			    hintStyle={{color:'#717171',fontSize:'15px',fontWeight:'300',bottom:'-1px'}}
				style={{height:'40px',lineHeight:'40px',margin:'0 16px',color:'#717171',backgroundColor:'#fff',fontWeight:'300',fontSize:'15px',padding:'1px 16px', border: '1px solid #dcddde',width: '200px', display:'inline-block',outline:'none'}}
				value={this.state.selectedCountry}
		        menuGroupStyle={{color:'#717171',fontWeight:'300'}}
		        innerDivStyle={{fontSize: '14px'}}
		        underlineStyle={{display:'none'}}
		        showAutocompleteThreshold={countryCount}
		        onChange = {this.handleSelection.bind(this)}
        	>
          		{countryList}
        	</SuperSelectField>

**Comment by Sharlaan** [comment]
Are you using latest version v1.6.0 ? (1.6.1 coming very soon)

> **showAutocompleteThreshold** | type: number | default value: 10
Maximum number of options from which to display the autocomplete search field.For example, if autoComplete textfield need to be disabled, just **set this prop with a value higher than children length**.

The bolded part means that, to display the autocomplete field, you just have to set this prop to some value lower than children length.
So the default should be enough if your country list has 10+ items.
Also if your data is fetched from a server, your countryCount will most probably have a value of 0 at component mount phase, effectively disabling the autocomplete, not what you want right ?

The idea is to prevent the autocomplete to show when all items are displayed within the menu container height, would be useless usage of space.

**Comment by tonysam** [comment]
Thank you, very much for clarifying. It was a mistake from my side. 
Thanks for patiently replying.
The material-ui-superselectfield  is simply an awesome component.

**Comment by Sharlaan** [comment]
Glad  you resolved the issue.
I admit this property might sound confusing sometimes.
