### ISSUE TITLE
How to sort menu list items alphabetically ?

### ISSUE THREAD

**Issue by shivwork** [Sharlaan/material-ui-superselectfield#78]

**Comment by Sharlaan** [comment]
See issue#75.
After some thoughts and by common agreeness with other contributors, we think this should not be the responsibility of the component to manipulate data.
SelectField is just a presenting component.
I'm aware this is kinda borderline, but this request **should be done on the developper side**.
You can set the sorted array as source, superSelectField will automatically detect if children changed -by sorting- and will rerender.
