### ISSUE TITLE
TypeError: Cannot read property 'baseTheme' of undefined

### ISSUE THREAD

**Issue by reszli** [Sharlaan/material-ui-superselectfield#79]
Hello,

I'm a newbie in React and Material and I'm having trouble using superselectfield

I'm using create-react-app to create a test application
then I removed everything from the src folder and added just the following in index.js

import React from 'react';
import ReactDOM from 'react-dom';
import CodeExample from './codeExample';

ReactDOM.render(
  <CodeExample />,
  document.getElementById('root')
);

where CodeExample is the code from https://github.com/Sharlaan/material-ui-superselectfield/blob/master/src/CodeExample1.js, but then I get the following error:

TypeError: Cannot read property 'baseTheme' of undefined SelectField.render
node_modules/material-ui-superselectfield/lib/SuperSelectField.js:642

  639 | // Default style depending on Material-UI context (muiTheme)
  640 | 
  641 | var _context$muiTheme = this.context.muiTheme,
  642 |     palette = _context$muiTheme.baseTheme.palette,
  643 |     menuItem = _context$muiTheme.menuItem;
  644 | 

The same happens if I add a superselectfield into my existing project.

my package.json looks like this:
  "dependencies": {
    "babel-polyfill": "^6.26.0",
    "material-ui": "^0.19.4",
    "material-ui-superselectfield": "^1.6.0",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-scripts": "1.0.14"
  },

What am I doing wrong?

Thanks in advance,
Istvan

**Comment by Sharlaan** [comment]
Issues section in Github is for bug reporting or enhancement suggestions, not for debugging your code.
I suggest you [StackOverFlow](https://stackoverflow.com/search?q=Material-ui)

Little hint: look in my index.js then follow the tree of components, instead of going straight to CodeExample sub-components.

**Comment by gilles-yvetot** [comment]
@Sharlaan, I am trying to port Superselectfield to material-ui v1 but I am struggling with this too. i have updated most of the project but as soon as I try to go on an example page, it is not working because of the context theme.
