### ISSUE TITLE
Button or something for the user to click when the selection (multiple) is finished

### ISSUE THREAD

**Issue by filipenevola** [Sharlaan/material-ui-superselectfield#8]
Hello @Sharlaan, we don't have any place for the user click when he finishes to select the values he wants.

Would be good to have a place (button, link, label) like Close or Finish for the user to click because in the multi select is confusing how the user can get out of it, on a mobile device is worst because we don't have a lot of space.

What do you think about that?

Another option is just to provide a callback for onOpen and onClose and with that we can show something for the user or not on our own.

Let me know what you think about it.

Thanks

**Comment by Sharlaan** [comment]
er... i thought it's common knowledge to just tap outside of the menu to autoclose it (and also the ESC key) ?
The exception being when the Select accepts only one selection, in that usecase the menu closes right after the selection.

On mobile device, isnot it common knowledge to use the "back" button to exit a menu taking whole page's width ?

I didnot find anything related to this kind of notification or helper in Google Material specs.

Honestly i could probably implement a last child containing such button with a handler triggering this.closeMenu(), but would be low priority, given common usage.

**Comment by filipenevola** [comment]
Hello @Sharlaan, I really don't know but I think it is not obvious for everybody. See my screen:

![selection_026](https://cloud.githubusercontent.com/assets/437372/23120036/01c1eaee-f75b-11e6-9b7c-c086189f1d36.png)

Do you really think your father or mother knows that is necessary to click on the white area below the selection?

If you have any suggestion for this UI would be nice.

**Comment by Sharlaan** [comment]
i just showed your screenshot to my old parents :
- my father didnot even understand it were a menu, and suggested if the background of the page were more contrasted vs. the white of the menu he may have got it...
- my mother just click on the red dot in upper right corner to close the menu.

i investigated a few other sites, and discovreed not a lot are using multivalues menu. Most seems ti prefer several monovalue dropdowns, or 1 monovalue dropdown with a link below "add another choice" popping another monovalue dropdown.
Might be more suitable to a mobile layout ?

**Comment by filipenevola** [comment]
Hummmm, I need to think more about it.

And nice test with your parents, thank you! :)

I release my first MVP today, let's wait feedbacks https://www.ondecolocomeudinheiro.com (it is only in portuguese because is a specific solution for Brazilians that want to invest money)

I'll close this for now.
