### ISSUE TITLE
How to customize scrollbar

### ISSUE THREAD

**Issue by greybutton** [Sharlaan/material-ui-superselectfield#86]
Hello, I want to use [https://github.com/malte-wessel/react-custom-scrollbars](https://github.com/malte-wessel/react-custom-scrollbars)
I tried use like
```
<Scrollbars>
  <SuperSelectField>
    {NodeList}
  </SuperSelectField>
<Scrollbars>
```
and it doesn't work.

I would very appreciate someone help me out about this. Thanks!

**Comment by Sharlaan** [comment]
You can't, since superselectfield is a component consisting of multiple sub-components, while your HoC is intended to be applied only on the internal Popover.js.
