### ISSUE TITLE
floatingLabel not working correctly in SingleSelect.

### ISSUE THREAD

**Issue by shivwork** [Sharlaan/material-ui-superselectfield#88]
<MaterialSelectField
      disabled={disabled ? disabled : false}
      showAutocompleteThreshold={1}
      errorText={touched && error}
      floatingLabel={label}
      value={selectedObj}
      nb2show={7}
      anchorOrigin={{ vertical: 'top', horizontal: 'left' }}
      required={true}
      onChange={(e) => changeSelectedObj(e)}
      hoverColor='rgba(3, 169, 244, 0.15)'
    >
      {optionsList}
    </MaterialSelectField>

**Comment by Sharlaan** [comment]
see #67
