### ISSUE TITLE
Question: waffle.io

### ISSUE THREAD

**Issue by FDiskas** [Sharlaan/material-ui-superselectfield#93]
Are you using https://waffle.io/Sharlaan/material-ui-superselectfield ?

**Comment by Sharlaan** [comment]
nope, what it is ?

**Comment by FDiskas** [comment]
For better issues handling - like Trello

**Comment by FDiskas** [comment]
![staticshot_10-11-2017_16-23-05](https://user-images.githubusercontent.com/468006/32662502-7a474d5e-c633-11e7-958e-c88e5d7f6056.png)

**Comment by Sharlaan** [comment]
Interesting for large projects, not for a simple component.
